# Calibration Offline Settings
input_dir: "D:/ylx/calib_records"
output_dir: "D:/ylx/calib_results"

# Gaze Tracker Settings
gaze_tracker:
  use_chen_noise_reduction: true   # 是否使用 Chen 降噪算法
  cc_filter:
    enable: false
    window_size: 5
  pc_filter:
    enable: false
    window_size: 5

# Camera Settings
cam_pos: [29.0, -31.0, 17.0]
cam_xml_path:
  - "D:/ylx/calib/cams/Camera_Data.xml"
#  - "D:/ylx/calib/cams/Camera1_Data.xml"
#  - "D:/ylx/calib/cams/Camera2_Data.xml"
cam_angles: [-31.5, 0.0, 0.0]

# Lights Settings
lights_pos:
 - [-21.0, 0.0, 0.0] # [21, 3, 0]
 - [25.0, 0.0, 0.0] # [-25, 3, 1]
 - [0.0, 8.0, 5.0] # [0, -8, 6]

# Calibration General Settings
calib_init_values:
  left:
    alpha: 5
    beta: 1.5
    R: 0.78
    K: 0.42
    n1: 1.3375
    n2: 1.0
    D: 0.53
  right:
    alpha: -5
    beta: 1.5
    R: 0.78
    K: 0.42
    n1: 1.3375
    n2: 1.0
    D: 0.53
  eye_cam_dist_init: 40.0

calib_values_bounds:
  alpha: [-5, 5]
  beta: [-5, 5]
  R: [0.4, 1.5]
  K: [0.1, 1.0]

# Screen Settings
screen_width_px: 2560
screen_height_px: 1440
screen_width_cm: 59.5
screen_height_cm: 33.6
screen_center: [-0.75, -20.99, -7.07]
screen_horizontal_direction: [-1.0, 0.0, 0.0]
screen_vertical_direction: [0.00, 0.85, -0.52]

# Visualization Settings
viz: true
viz_output_dir: "D:/ylx/calib_viz"

# Test one cam
test_one_cam:
  cam_index: 40061061
  save_dir: "D:/ylx/test_one_cam"
  fps: 90
  gain: 0.0
  gamma: 1.0
  exposure_time: 10000.0
  frame_width: 720
  frame_height: 540

# Test multi cam
test_multi_cam:
  cam_indices:
    - 40061061
    - 40061280
    - 40109652
  save_dir: "D:/ylx/test_multi_cam_75mm"
  fps: 90
  gain: 0.0
  gamma: 1.0
  exposure_time: 10000.0
  window_width: 1440
  window_height: 1080

# Test glint
test_glint:
  local_debug: false
  num_images: 100
  input_folder: "D:/ylx/glint_input/front/3_3"
  output_folder: "D:/ylx/glint_input/front/3_3/viz"
  gaussion_kernel_size: 3
  laplician_kernel_size: 1
  threshold: 125.0

collect_glint:
  is_collecting: true
  local_debug: false
  num_images: 100
  input_folder: "D:/ylx/glint_input/collect_input"
  output_folder: "D:/ylx/glint_input/collect_output"

relaxed_glint_hyperparameter:
  horizontal_pair:
    lr_y_min: 0
    lr_y_max: 7
    lr_x_min: 5
    lr_x_max: 20

    extention_x_min: 2
    extention_x_max: 2
    extention_y_min: 2
    extention_y_max: 2

  middle_point:
    conditions:
      - [0, 2, 0.2, 0.8, 0.05, 0.55, 0.2, 0.8, 0.05, 0.55]
      - [2, 3, 0.45, 0.7, 0.05, 0.25, 0.3, 0.55, 0.25, 0.5]
      - [3, 5, 0.45, 0.85, 0.04, 0.25, 0.15, 0.55, 0.3, 0.65]
    extention_lm_x/lr_x_min: 0.05
    extention_lm_x/lr_x_max: 0.05

    extention_lm_y/lr_x_min: 0.05
    extention_lm_y/lr_x_max: 0.05

    extention_rm_x/lr_x_min: 0.05
    extention_rm_x/lr_x_max: 0.05

    extention_rm_y/lr_x_min: 0.05
    extention_rm_y/lr_x_max: 0.05
    
  
glint_hyperparameter:
  horizontal_pair:
    lr_y_min: 0.000000
    lr_y_max: 6.750000
    lr_x_min: 7.000000
    lr_x_max: 17.500000

  middle_point:
    conditions:
      - [0, 2, 0.337097, 0.646154, 0.0928571, 0.322727, 0.353846, 0.662903, 0.142308, 0.357692]
      - [2, 3, 0.459804, 0.688889, 0.0676471, 0.244444, 0.311111, 0.540196, 0.228689, 0.511538]
      - [3, 5, 0.49, 0.887838, 0.0310811, 0.175, 0.112162, 0.51, 0.29, 0.644595]
test_glint_hyperparameter:
  horizontal_pair:
    lr_y_min: 1.000000
    lr_y_max: 5
    lr_x_min: 7
    lr_x_max: 16

  middle_point:
    conditions:
      - [-1, 2, 0.2, 0.8, 0.05, 0.55, 0.2, 0.8, 0.05, 0.55]
      - [2, 3, 0.45, 0.7, 0.05, 0.25, 0.3, 0.55, 0.25, 0.5]
      - [3, 5, 0.45, 0.85, 0.04, 0.25, 0.15, 0.55, 0.3, 0.65]
